# Generated by Django 5.2 on 2026-02-05 02:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(fields=('shift', 'location'), name='unique_shift_location'),
        ),
    ]
